In [4]:
import numpy as np

In [5]:
np.__version__

'2.4.6'

In [9]:
import sys

In [10]:
sys.version

'3.14.6 | packaged by Anaconda, Inc. | (main, Jul  9 2026, 14:29:05) [MSC v.1942 64 bit (AMD64)]'

In [12]:
my_list=[0,1,2,3,4]
my_list

[0, 1, 2, 3, 4]

In [13]:
type(my_list)

list

In [15]:
arr= np.array(my_list)
arr

array([0, 1, 2, 3, 4])

In [16]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [19]:
np.arange(20,10)

array([], dtype=int64)

In [20]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [21]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [17]:
C # parametertunning


array([0., 0., 0., 0., 0.])

In [19]:
np.ones(5) # parametertunning

array([1., 1., 1., 1., 1.])

In [20]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [23]:
np.twos(5,dtype=int) #numpy has no attribute 2,3...

AttributeError: module 'numpy' has no attribute 'twos'

In [24]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
np.zeros((10,3),dtype=int) # by default 10-rows& 3-columns

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
np.ones(4)

array([1., 1., 1., 1.])

In [32]:
np.random.rand(2,3) 

array([[0.05130598, 0.97965112, 0.96057116],
       [0.18677859, 0.17862692, 0.30690974]])

In [33]:
np.random.rand(2) # it will give float

array([0.08896259, 0.61095926])

In [34]:
np.random.randint(2)  # it will generate random int between 0 & n-1

1

In [35]:
np.random.randint(2,3) # it will generate random int between 0 & n-1

2

In [36]:
np.random.randint(2,9) # random no. betwn 2,,3,4,5,6,7,8

6

In [41]:
np.random.randint(2,9,4) #t will generate random int between 2-9 where 9 is exclude

array([5, 3, 6, 7], dtype=int32)

In [45]:
import numpy as np

otp = np.random.randint(1, 6)
print("Your OTP is:", otp)

Your OTP is: 5


In [50]:
import numpy as np
def generate_otp(length=6):
    otp= ''.join([str(np.random.randint(0,10))for_in range(length)])
    return otp
    print('Your OTP is:',generate_otp())

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3518510917.py, line 3)

In [51]:
np.thousands(2)

AttributeError: module 'numpy' has no attribute 'thousands'

# Array creation

In [52]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [54]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [56]:
f=np.eye(4)
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array manipulation 

In [3]:
import numpy as np

In [58]:
a1=np.array([1,2,3])
reshaped= np.reshape(a1,(3,1))
print("Reshaped arrya:",reshaped)

Reshaped arrya: [[1]
 [2]
 [3]]


In [60]:
# transposed array
e1=np.array([[1,2],[3,4]])
transposed= np.transpose(e1)
print("transposed array:\n",transposed)


transposed array:
 [[1 3]
 [2 4]]


In [62]:
# stacked array
a2=np.array([1,2])
b2=np.array([3,4])
stacked= np.hstack([a2,b2])
print("stacked arrays:\n",stacked)

stacked arrays:
 [1 2 3 4]


In [2]:
 # Flatten an array
f1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened array:", flattened)

NameError: name 'np' is not defined

# mathematical functions

In [63]:
# add two arrays
g=np.array([1,2,3,4])
added=np.add(g,2)
print("added g", added)

added g [3 4 5 6]


In [64]:
squared=np.power(g,2)
print("squared g", squared)

squared g [ 1  4  9 16]


In [65]:
a3=np.array([1,2,3,4])
dot_product=np.dot(a,g)
print("dot product of a1 and a:", dot product)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1594326430.py, line 3)

In [67]:
#mean variation
s=np.array([1,2,3,4])
mean=np.mean(s)
print("mean of s:",mean)

mean of s: 2.5


In [70]:
s=np.array([1,2,3,4])
var=np.var(s)
print("Variance of s:",var)

Variance of s: 1.25


In [72]:
s

array([1, 2, 3, 4])

In [76]:
minimum=np.min(s)
print ("minimum of s:",min)

minimum of s: <built-in function min>
