In [14]:
import numpy as np

In [8]:
np.__version__

'2.4.6'

In [9]:
import sys

In [10]:
sys.version

'3.14.6 | packaged by Anaconda, Inc. | (main, Jul  9 2026, 14:29:05) [MSC v.1942 64 bit (AMD64)]'

In [12]:
my_list=[0,1,2,3,4]
my_list

[0, 1, 2, 3, 4]

In [13]:
type(my_list)

list

In [15]:
arr= np.array(my_list)
arr

array([0, 1, 2, 3, 4])

In [16]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [19]:
np.arange(20,10)

array([], dtype=int64)

In [20]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [21]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])